import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Bebas_Neue, Roboto, Alegreya_SC, Inria_Serif } from 'next/font/google'
import { Toaster } from 'react-hot-toast';

const bebas = Bebas_Neue({ subsets: ['latin'], weight: '400', variable: '--font-bebas' })
const roboto = Roboto({ subsets: ['latin'], weight: '400', variable: '--font-roboto' })
const alegreya = Alegreya_SC({ subsets: ['latin'], weight: '400', variable: '--font-alegreya' })
const inria = Inria_Serif({ subsets: ['latin'], weight: '400', variable: '--font-inria' })

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${bebas.variable} ${roboto.variable} ${alegreya.variable} ${inria.variable}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster position="top-right" />
        {children}
      </body>
    </html>
  );
}
